### PR TITLE
Reformat to 180 line length

### PR DESCRIPTION
**Pull request by fboundy**
No changes other than a max line length of 180.

### CODE REVIEW

**Review by springfall2008 — APPROVED** [review]

**Comment by springfall2008** [comment]
This probably means creating new dev branches as it's going to conflict with any changes made prior to the reformat

**Comment by iainfogg** [comment]
You shouldn't need to create a new dev branch, you can merge `main` into your dev branch, and you'll need to deal with any conflicts at that point.

Or recreate the dev branch if that's easier than dealing with the merge conflicts.

**Comment by springfall2008** [comment]
Sure, that could work too. I just delete my dev branches after each merge

**Comment by fboundy** [comment]
Not sure there are many outstanding dev branches at present anyway

**Pull request merged**
