### PR TITLE
Added missing entities to example dashboard to match latest predbat releases

### PR DESCRIPTION
**Pull request by gcoan**

### CODE REVIEW

**Comment by springfall2008** [comment]
I can only see car_charging_start missing, the other two appear to be there?

**Comment by gcoan** [comment]
Well I didn’t make them up!  I was going through the latest releases making sure I had all the new entities in my own dashboard.
I added them as 3 separate commits to the dashboard, one for each release I fo7nd missing entities 🤷‍♂️

Geoffrey

**Comment by iainfogg** [comment]
Two of the entities were already there, and are there twice now

**Comment by gcoan** [comment]
Don't understand how I thought two of the entities were missing but they are there.
Anyway, they are there in the latest code, so added extra commits to remove the duplicates I added

**Comment by gcoan** [comment]
Closing pull request as car_charging_start has been added by Trevor

**Pull request closed without merging**
