### PR TITLE
Add solar assistant to predbat

### LINKED ISSUE #786: Add support for Solar Assistant
Would be great to have support for Solar Assistant ( https://solar-assistant.io/ ). It supports many types of inverters and the beta version has a proper power management that works fine with Growatt (my case) inverters as well.
I saw another issue opened here for Huaweii ( #684 )  so I will try to play a bit with the template yaml and see where I get, just wanted to get this on the radar (and also confirm if this is something doable or not).
Thanks!

### PR DESCRIPTION
**Pull request by xhemp**
Added Solar Assistant to PredBat. 
I believe this will help whoever wants to use PredBat with Solar Assistant and would allow people (like me) to upgrade to new versions without modifying the config.py.
This resolves #786

### CODE REVIEW

**Comment by springfall2008** [comment]
Nice one :) Any chance of you adding it to the documentation too?

**Comment by xhemp** [comment]
Sure thing, will do as soon as I get home.
-------- Original Message --------On 12/12/2024 19:47, Trefor Southwell  wrote:
Nice one :) Any chance of you adding it to the documentation too?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/springfall2008/batpred/pull/1723#issuecomment-2539876075",
"url": "https://github.com/springfall2008/batpred/pull/1723#issuecomment-2539876075",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sparkyhughes** [comment]
Any chance this can be enhanced to enable more features via Solar-Assistant exposed MQTT entities? The Mode works fine now, but SOC Target and Discharge rate has no effect from what I can see as setting the discharge rate to 0 doesn’t stop the battery discharging. Maybe if more of the batpred variables which can be tied to HA entities were known and documented in the apps.yaml file?

**Comment by xhemp** [comment]
@sparkyhughes Not sure if you can set that on Solar Assistant, I went through the MQTT topics and I can't see anywhere to set a SOC target. For charge/discharge rate, I can see topics but they are in percentage for Solar Assistant and looks like they are in watts in batpred. Have you tried to play with those topics and see what happened?

**Comment by sparkyhughes** [comment]
I've managed to get Batpred setting the Battery First Stop Charge value by using the charge_limit setting:
 ```
charge_limit:
    - number.growatt_sph_battery_first_stop_charge
```

I've also managed to get charge freeze working by modifying the start/stop/freeze service settings

  ```
# Service for start/stop
  charge_start_service:
    - service: select.select_option
      entity_id: select.growatt_sph_work_mode_priority
      option: "Battery first"
    - service: select.select_option
      entity_id: select.growatt_sph_battery_first_grid_charge
      option: "Enabled"
  charge_stop_service:
    service: select.select_option
    entity_id: select.growatt_sph_work_mode_priority
    option: "Load first"
  discharge_start_service:
    service: select.select_option
    entity_id: select.growatt_sph_work_mode_priority
    option: "Grid first"
  charge_freeze_service:
    - service: select.select_option
      entity_id: select.growatt_sph_battery_first_grid_charge
      option: "Disabled"
    - service: select.select_option
      entity_id: select.growatt_sph_work_mode_priority
      option: "Battery first"
```
I needed to enable charge freeze and charge limit in the config.py file, which will be overwritten I presume when Batpred is next upgraded?

I set "has_target_soc" to True
I set "support_charge_freeze" to True

**Comment by xhemp** [comment]
Nice one, @sparkyhughes, I have added on mine and will see what happens.
You are right, you would need to change config.py again with that after an update but that's until we test it works properly, either one of us can open a PR to add that and after it gets merged, we won't need to change anything else.
There's also something which I believe we will need @springfall2008 's help, I get the following error on the Status:

`
Error: Exception raised 'NoneType' object has no attribute 'split'
`

And on the logs:

`
2024-12-19 10:15:21.186310: Error: Exception raised 'NoneType' object has no attribute 'split'
2024-12-19 10:15:21.187935: Error: Traceback (most recent call last):
  File "/config/predbat.py", line 965, in run_time_loop
    self.update_pred(scheduled=True)
  File "/config/predbat.py", line 556, in update_pred
    status, status_extra = self.execute_plan()
  File "/config/execute.py", line 454, in execute_plan
    self.adjust_battery_target_multi(inverter, 0, isCharging, isExporting)
  File "/config/execute.py", line 498, in adjust_battery_target_multi
    inverter.adjust_battery_target(new_soc_percent, is_charging, is_exporting)
  File "/config/inverter.py", line 1243, in adjust_battery_target
    self.write_and_poll_value("charge_limit", self.base.get_arg("charge_limit", indirect=False, index=self.id), soc)
  File "/config/inverter.py", line 1307, in write_and_poll_value
    domain, entity_name = entity_id.split(".")
AttributeError: 'NoneType' object has no attribute 'split'

2024-12-19 10:15:21.237717: Info: record_status Error: Exception raised 'NoneType' object has no attribute 'split'
2024-12-19 10:15:21.237916: Error: 'NoneType' object has no attribute 'split'
`

Do you get that as well @sparkyhughes ?

**Comment by sparkyhughes** [comment]
No I don't get that error.  Is that in the Predbat log (on the HA Add-ons page -> Log) ?
I just get the usual "Warn: Inverter 0: Using Inverter type SA - not all features are available" and "Info: record_status Demand"

There's another useful log in File Editor in the same directory as apps.yaml called predbat.log which has quite verbose stuff logged.

**Comment by sparkyhughes** [comment]
I think because Solar-Assistant supports so many different inverters, it's almost like a separate version for each inverter type is needed.  Luckily you and I have Growatt albeit slightly different inverter model

**Comment by xhemp** [comment]
> No I don't get that error. Is that in the Predbat log (on the HA Add-ons page -> Log) ? I just get the usual "Warn: Inverter 0: Using Inverter type SA - not all features are available" and "Info: record_status Demand"
> 
> There's another useful log in File Editor in the same directory as apps.yaml called predbat.log which has quite verbose stuff logged.

Yes, there or in the predbat page - logs but then you have to set it to All to see all errors.
So just with the same configuration (in your case, you probably changed the apps.yaml to sph instead of spa), you see no errors at all? It's odd. 
Maybe it's time to open a new issue so we can talk there instead of in this PR.

**Comment by xhemp** [comment]
Opened https://github.com/springfall2008/batpred/issues/1761 , we can continue there.

**Comment by xhemp** [comment]
@springfall2008 any chance you can have a look at #1761 ?

**Pull request merged**
