### PR TITLE
Set up documentation site

### LINKED ISSUE #276: Documentation rework
Hi @springfall2008 

As the project has grown in features and complexity, I think the README has now got really long, and isn't ideal for people finding their way around it.

What do you think about reworking the content of the README file into a proper documentation site? I'm suggesting using `mkdocs` along with GitHub Pages, and using a CI pipeline to build and publish the docs each time there's a new commit pushed to `master` (or I expect you could also do it on new tags instead).

I'd be happy to have a crack at doing this for you, I've used `mkdocs` before, although I think I'd probably need some permissions temporarily on your repo to do it to configure the settings and publishing. Or obviously feel free to go at it yourself :)

It'd involve taking the content of the current README and breaking it into separate files, and each file would be a separate page in the documentation site. I'd recommend using the `readthedocs` theme within `mkdocs`, so it'd look the same as this site:

https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html

I think it'd make it a lot easier for people to make use of the content that's currently in the README.

What do you reckon?

### PR DESCRIPTION
**Pull request by iainfogg**
This PR takes the existing content from the README and breaks it down into separate files in the `docs` folder, publishing them using GitHub Pages and GitHub Actions.

The aim is to create a more easily accessible, and searchable, site than the current very long README.

It uses `mkdocs` to build the HTML pages for the documentation site, based on the Markdown files.

`mkdocs.yml` defines the navigation bar at the side (this allows controlling the order of pages, which would otherwise be in alphabetic order), and also sets the theme and other settings.

Closes #276

### CODE REVIEW

**Review by springfall2008 — APPROVED** [review]

**Comment by springfall2008** [comment]
So far looks good, just noticed it was draft actually

**Comment by iainfogg** [comment]
Yep, I was just creating the PR to check that I had permissions to do it 😃

I'll let you know when it's done.

**Comment by springfall2008** [comment]
I guess we could rebuild on release?

**Comment by iainfogg** [comment]
Thanks, I'll sort the config for that.

Yep, I think building on a release makes sense.

**Comment by iainfogg** [comment]
See #276 for latest changes.

I'm happy with this if you are.

**Pull request merged**
