### PR TITLE
Documentation updates, rewrite car charging, output data & code fixes to pathnames

### PR DESCRIPTION
**Pull request by gcoan**
Documentation changes:
- Solcast documentation, add to apps.yaml, error 429 in FAQ, multiple Solcast accounts
- Output data changes, rewrite explanations of how to create a simple dashboard and the auto-generated collapsible dashboard
- Add Instructions for upgrading to predbat add-on
- Changed Predbat manual install for split predbat.py
- Formatting tidy-up's
- Fix missing '<serial_number> type markups
- Extended PV10/50/90 description
- Restructure all car charging config into one document
- Clarified that predbat entities are for the forecast_hours duration #1202 
- Correct template YAML indentation #1257 
- Add car_charging_exclusive to apps-yaml.md for release 8.2.0 #1270 
- Add tip to use IP address instead of HA URL when setting the ha_url

Code changes:
- Round current inverter charge/discharge rates in log
- Write predbat_dashboard when Template still set #1221 
- Change logfile references to AppDaemon (e.g. time out of sync) to be more generic
- Write full hierarchical paths in logfile rather than /config mount #1229 
- Remove extra / from Solcast pathname, e.g. https://api.solcast.com.au//rooftop_sites

NB: The code changes for #1229 require Predbat to work out what add-on it is running within to determine the correct full hierarchical pathname. This has been tested on AppDaemon and Predbat add-on's but not with Predbat running as a separate docker. It should work, but hasn't been tested.

### CODE REVIEW

**Review by springfall2008 — APPROVED** [review]

**Comment by springfall2008** [comment]
Changes look good, but conflicts need resolving, do you know how to do that on the command line?

**Comment by gcoan** [comment]
> Changes look good, but conflicts need resolving, do you know how to do that on the command line?

No I'm only really used to using the web front end to github but I can try to work out what they are and what is needed to resolve them.  My changes were against predbat v8.0.0, so there will be your latest changes, some of which must clash with mine.

Well done on the Gary does Solar interview BTW, good publicity and hopefully should help grow the community.

**Comment by gcoan** [comment]
> Changes look good, but conflicts need resolving, do you know how to do that on the command line?

Hi @springfall2008 I am struggling ...

Have installed git locally on my PC, sync'd my fork onto my PC and through the Git Gui I can see my branch history and changes correctly.

But I just don't know how to (1) see the conflicts in git command line or (2) resolve them.

[I could see the changes between my fork based on v8.0.0 and your main v8.2.4 in the GUI, and there are extensive changes you've made, but other than manually copy/pasting all your changes into my fork, that doesn't help me]

The PR says:
image

From the Git Gui on my PC, I do Repository/Git Bash

Paste the step 1 lines in:

image

Now what do I do, how do I see/act upon the merge conflicts?

If I try the step 2 commands it has nothing to push, presumably as I've not made any changes:

image

I think I'm supposed to be making changes to resolve the merge conflict between steps 1 and 2.
Git should be able to merge my branch even if we have both changed the same file, I can understand that if we've both changed the same line then it gets confused, but I don't see a way to be able to view those detailed and specific conflicts.

**Comment by gcoan** [comment]
Hello again @springfall2008 here's an update on branch conflicts Github identifies in this PR:

- apps/predbat/inverter.py - I have copied across the latest inverter.py from springfall2008:main and re-applied all my changes.  It should be safe to just accept my version as-is
- apps/predbat/predbat.py - Ditto, copied from your main and re-applied all my changes

- docs/car-charge-planning.md - this has been renamed to car-charging.md and now incorporates the car charging stuff that was previously in customisation.md.  I have reviewed the differences and I had already copied across your latest car charging changes into my fork, so you can replace the main version with mine
- docs/apps-yaml.md - ditto, primary changes are due to car charging rewrites. Have reviewed the compare and you can take my copy across
- docs/customisation.md - ditto, have reviewed the changes and you can take my copy across

- templates/givenergy_cloud.yaml - this was a tidy up of the formatting, removing some stuff not relevant (like REST). I had also applied the typo correction you had made, so again safe to take my copy across

- templates/sunsynk.yaml - this was a tidy up of formatting but you have expanded it with the PR for sunsync documentation, so just reject my changes to this file and I can rework later on

**Comment by gcoan** [comment]
Hi Trefor @springfall2008 how you getting on with my PR?  Am feeling that I'm falling further behind the latest code with this outstanding.

Are you able to merge it manually?

Thanks Geoffrey

**Comment by springfall2008** [comment]
I'll have a go merging this when I get back from holiday

**Comment by gcoan** [comment]
> I'll have a go merging this when I get back from holiday

thanks

**Pull request merged**
